version: '3'

services:
  server:
    container_name: "flask-server"
    ports:
      - "5000:5000"
    build:
      context: .
    volumes:
      - ./data/:/usr/src/app/data
    restart: on-failure:3

